### ISSUE TITLE
Cannot find module '../model/User'

### ISSUE THREAD

**Issue by mohammadjassem1993** [asemammar/medicalApp#2]
node     | node:internal/modules/cjs/loader:926
node     |   throw err;
node     |   ^
node     | 
node     | Error: Cannot find module '../model/User'
node     | Require stack:
node     | - /app/routes/treatments.js
node     | - /app/index.js
node     |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:923:15)
node     |     at Function.Module._load (node:internal/modules/cjs/loader:768:27)
node     |     at Module.require (node:internal/modules/cjs/loader:995:19)
node     |     at require (node:internal/modules/cjs/helpers:92:18)
node     |     at Object.<anonymous> (/app/routes/treatments.js:6:14)
node     |     at Module._compile (node:internal/modules/cjs/loader:1091:14)
node     |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
node     |     at Module.load (node:internal/modules/cjs/loader:971:32)
node     |     at Function.Module._load (node:internal/modules/cjs/loader:812:14)
node     |     at Module.require (node:internal/modules/cjs/loader:995:19)
node     |     at require (node:internal/modules/cjs/helpers:92:18)
node     |     at Object.<anonymous> (/app/index.js:27:25)
node     |     at Module._compile (node:internal/modules/cjs/loader:1091:14)
node     |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
node     |     at Module.load (node:internal/modules/cjs/loader:971:32)
node     |     at Function.Module._load (node:internal/modules/cjs/loader:812:14) {
node     |   code: 'MODULE_NOT_FOUND',
node     |   requireStack: [ '/app/routes/treatments.js', '/app/index.js' ]
node     | }

**Comment by mohammadjassem1993** [comment]
Fixing it by changing the User to user for each js file.

**Comment by asemammar** [comment]
issue fixed via refactoring
